<?php 
include_once("../model/pdo.php");
include_once("../model/loai.php");
include_once("../model/san-pham.php");
include_once("../model/toast-message.php");
include_once("../model/detail-san-pham.php");
include_once("../model/do-an-them.php");
include_once("../model/khau-phan.php");
include_once("../model/roles.php");
include_once("../model/user.php");
include_once("../model/roles.php");
include_once("../model/binh-luan.php");
include_once("../model/giam-gia.php");
include_once("../model/don-hang.php");
include_once("../model/chi-tiet-don-hang.php");
include_once("../model/trang-thai-don.php");
include_once("../model/danh-gia.php");
include_once("../model/thong-ke.php");
?>